structure Mirror =
struct
    val smackage = "/Users/gdpe/Documents/code/smackage/bin/smackage"
    val smackageHome = "/Users/gdpe/.smackage"
    val dataRoot = "/Library/WebServer/CGI-Executables/data"

    fun versionMap f res =
        (List.map 
            (fn (n,dict) => 
                (List.map (fn (k,_) => f (n,k) 
            ) (List.rev (SemVerDict.toList dict)))) res) 

    fun retrSpec (pkg,ver) =
    let
        val _ = OS.Process.system 
            (smackage ^ " get " ^ pkg ^ " " ^ SemVer.toString ver)
        
        val s = SmackLib.info smackageHome (pkg,ver) handle _ =>
            [Spec.Provides (pkg,ver),
             Spec.Key ("comment", "Automated stub spec generated by mirror.sml")]

        val s' = 
        let
            val _ = Spec.provides s
        in
            s
        end handle _ => Spec.Provides (pkg,ver) :: s

        val fo = TextIO.openOut (dataRoot ^ "/" ^ pkg ^ ".smackspec-v" ^
                    SemVer.toString ver)

        val _ = TextIO.output (fo, Spec.toString s')

        val _ = TextIO.closeOut fo

        val _ = print ("Wrote: " ^ dataRoot ^ "/" ^ pkg ^ ".smackspec-v" ^
                    SemVer.toString ver ^ "\n")
    in
        s'
    end

    fun main () =
    let
        val _ = OS.Process.system (smackage ^ " refresh")

        val _ = VersionIndex.init "/Users/gdpe/.smackage"

        val res = VersionIndex.search ""

        val _ = versionMap retrSpec res
    in
        OS.Process.success
    end
end

val _ = Mirror.main ()

